# https://embarkstudios.github.io/cargo-deny/

[licenses]
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "MPL-2.0",        # Mozilla Public License 2.0 (used by colored crate)
    "Unicode-3.0",    # Unicode License v3 (used by unicode-ident)
    "ISC",            # ISC License (used by inotify crates)
    "CC0-1.0",        # Creative Commons Zero v1.0 Universal (used by notify)
]

# Confidence threshold for detecting a license from a license text.
confidence-threshold = 0.8

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"

# The graph highlights used when creating dotgraphs for crates
# with multiple versions
highlight = "all"

# List of crates that are allowed. Use with care!
allow = []

# List of crates to deny
deny = []

# Certain crates/versions that will be skipped when doing duplicate detection.
skip = []

# Similarly to `skip` allows you to skip certain crates from being checked. Unlike `skip`,
# `skip-tree` skips the crate and all of its dependencies entirely.
skip-tree = []

[advisories]
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"

# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]

# The lint level for crates that have been yanked from their source registry
yanked = "warn"

# A list of advisory IDs to ignore. Note that ignored advisories will still
# output a note when they are encountered.
ignore = []

[sources]
# Lint level for what to happen when a crate from a crate registry that is
# not in the allow list is encountered
unknown-registry = "warn"

# Lint level for what to happen when a crate from a git repository that is not
# in the allow list is encountered
unknown-git = "warn"

# List of URLs for allowed crate registries. Defaults to the crates.io index
# if not specified. If it is specified but empty, no registries are allowed.
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

# List of URLs for allowed Git repositories
allow-git = []